kind: source
spec:
  name: "counts"
  registry: "grpc"
  path: "localhost:7777"
  tables: ['*']
  destinations: ["sqlite"]
  spec:
    base_url: https://api.mantelgroup.nullify.ai
    github_owner_id: 6890923
    access_token: "${NULLIFY_API_BEARER_TOKEN}"
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: "v2.4.11"
  spec:
    connection_string: ./db.sqlite